Get A Job/Entities/Applicants.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using Get_A_Job.Models;

namespace Get_A_Job.Entities
{
	public class Applicants
	{
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; } 
        public string OtherNames { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phonenumber { get; set; }
        public string State { get; set; }
        public DateTime DateCreated { get; set; }
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }
    }
}

Get A Job/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Get_A_Job.Controllers
{
    public class ApplicantController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
    }
}

Get A Job/Controllers/JobApplicationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Get_A_Job.Interfaces;
using Get_A_Job.Models;
using Microsoft.AspNet.Identity;

namespace Get_A_Job.Controllers
{
	public class JobApplicationController : Controller
	{


		IJobApplication ijobApplication;
		IApplicant iapplicant;
		private string userId;

		public JobApplicationController(IJobApplication jobApplication, IApplicant applicant)
		{
			ijobApplication = jobApplication;
			iapplicant = applicant;
		}

		public string UserId
		{
			get
			{
				return userId ?? HttpContext.User.Identity.GetUserId();
			}
			set
			{
				userId = value;
			}
		}

		public ActionResult AllJobs()
		{
			var jobs = ijobApplication.GetAllJobOffers("short");

			return View(jobs);
		}


		public ActionResult JobsDetail(int jobId)
		{
			var jobs = ijobApplication.GetAJobOffer(jobId);

			return View(jobs);
		}

		[Authorize]
		public ActionResult ApplicationForm(int jobId)
		{
			var userDetails = iapplicant.GetApplicantsDetails(UserId);
			userDetails.JobID = jobId;

			return View(userDetails);
		}

		[HttpPost]
		[Authorize]
		public ActionResult ApplicationForm(ApplicationFormViewModel applicationForm,
			HttpPostedFileBase file1, HttpPostedFileBase file2)
		{

			try
			{

				if (file2.ContentLength > 0 && file1.ContentLength > 0)
				{
					String FileExt1 = Path.GetExtension(file1.FileName).ToUpper();
					String FileExt2 = Path.GetExtension(file2.FileName).ToUpper();

					if (FileExt1 == ".PDF" && FileExt2 == ".PDF")
					{
						applicationForm.CV = file1;
						applicationForm.Letter = file2;
						if (ModelState.IsValid)
						{
							var res = ijobApplication.SubmitApplication(applicationForm, file2.FileName, UserId, file1.FileName);
							if (res == "Success")
							{
								ViewBag.ModelMessage = "Submit Succesfull";
							}
							else
							{
								ViewBag.ModelMessage = "Submit Unuccesfull";
							}
						}
						else
						{
							ViewBag.ModelMessage = "Empty fields";
							ModelState.AddModelError("", "Empty Feilds");
							return View(applicationForm);
						}
					}
					else
					{

						ViewBag.FileStatus = "Invalid file format.";
						return View();

					}



				}
				else
				{
					ViewBag.ModelMessage = "Please Upload a CV And Letter";
					return View(applicationForm);

				}
			}
			catch (Exception e)
			{
				ViewBag.ModelMessage = "ERROR:  " + e.Message.ToString();
			}
			return View();
		}


		//	[HttpGet]
		//public FileResult DownLoadFile(int id)
		//{
		////	var file = iapplicant.

		//	return File(file.FileContent, "application/pdf", file.FileName);

		//}
	}
}

Get A Job/Views/Applicant/Index.cshtml
@{
    ViewBag.Title = "Menu";
}

    <div class="container" style="margin-top:15px;">
        <div class="list-group">
            <div class="list-group-item">
                <i class="fa fa-home fa-fw" style="color:blue;"></i> @Html.ActionLink("Job Offers", "AllJobs", "JobApplication", routeValues: null, htmlAttributes: new { id = "registerLink" })
            </div>
            <a href="#" class="list-group-item"><i class="fa fa-book fa-fw"></i> Library</a>
            <a href="#" class="list-group-item"><i class="fa fa-pencil fa-fw"></i> Applications</a>
            <a href="#" class="list-group-item"><i class="fa fa-cog fa-fw"></i> Settings</a>
        </div>


        @*
         <div class="row">

            <div class="col-md-6 text-center" style="padding: 10px; align-content:center; justify-items:center;">
                <i class="fa fa-download fa-fw" style="font-size: 100px; color: green;"></i>
                <h3>
                    Accepted Applications
                </h3>
                <h6>
                    0
                </h6>
            </div>
            <div class="col-md-5 text-center">
                <i class="fa fa-eject fa-fw" style="font-size: 100px; color: yellow;"></i>
                <h3>
                    Pending Applications
                </h3>
                <h6>
                    0
                </h6>
            </div>

        </div>

        <div class="row">

            <div class="col-md-6 text-center" style="padding: 10px; align-content:center; justify-items:center;">
                <i class="fa fa-anchor fa-fw" style="font-size: 100px; color: red;"></i>
                <h3>
                    Rejected Applications
                </h3>
                <h6>
                    0
                </h6>
            </div>
            <div class="col-md-5 text-center">
                <i class="fa fa-asterisk fa-fw" style=" font-size: 100px;
            color: #007bff;"></i>
                <h3>
                    Unknown Applications
                </h3>
                <h6>
                    0
                </h6>
            </div>

        </div>

        *@


    </div>